# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/j6security?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate/JPA Configuration (Optional but common)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Oath2 Client Configuration
spring.security.oauth2.client.registration.google.client-id=98065421628-o734sluarccb6lga4d9eimfkg9bv7f4m.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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